import {lazy,Suspense,useEffect,useState} from 'react'
import {ArrowLeft,ArrowRight,Check,CheckCheck,Copy,Download,Layers,LoaderCircle,Plus,Redo2,Save,Sparkles,Undo2} from 'lucide-react'
import {applyAtelier,baseNail,duplicateDesign,finishNames,fingerNames,nailName,newDesign,shapeNames,targets,updateNails} from '../shared/design'
import type {Decoration,Nail,Scope} from '../shared/design'
import {HandPreview,NailArt,updateDecoration} from './NailArt'
import {api,useStudio} from './useStudio'
import type {SavedDesign} from './useStudio'
import {Dialog,exportDesign} from './Widgets'
import {ToolPanel} from './ToolPanel'
import {JewelPreview} from './JewelPreview'
import {MaterialLabBoundary} from './MaterialLabBoundary'
import {GesturePreview} from './GesturePreview'
import type {Arrangement} from './gestureLayout'
import {PatternStackControls} from './PatternStackControls'
import {nailPatterns,patternPatch} from '../shared/patternLayers'
import {DesignLayers,PriceDetails} from './DesignDetails'
import {designSummary,previewWithoutLayers,updateEditableNails} from '../shared/designDetails'
import {InspirationLibrary} from './InspirationLibrary'
import './App.css'

const MaterialLab=lazy(()=>import('./MaterialLab'))

export default function App(){
 const [materialLab,setMaterialLab]=useState(()=>new URLSearchParams(window.location.search).get('preview')==='material')
 const studio=useStudio(),{design,commit,ready,status,error}=studio
 const [selected,setSelected]=useState(1),[scope,setScope]=useState<Scope>('single')
 const [view,setView]=useState<'single'|'five'|'set'|'hand'>('set'),[side,setSide]=useState<'left'|'right'>('left')
 const [arrangement,setArrangement]=useState<Arrangement>(()=>{try{const v=localStorage.getItem('nail-preview-arrangement-v2');return v==='original'||v==='cupped'?v:'jewel'}catch{return 'jewel'}})
 function changeArrangement(value:Arrangement){setArrangement(value);try{localStorage.setItem('nail-preview-arrangement-v2',value)}catch{/* Preview choice remains usable without local storage. */}}
 const [tool,setTool]=useState('color'),[gallery,setGallery]=useState(false),[saved,setSaved]=useState<SavedDesign[]>([])
 const [galleryLoading,setGalleryLoading]=useState(false),[galleryError,setGalleryError]=useState('')
 const [inspire,setInspire]=useState(false),[confirm,setConfirm]=useState<'reset'|'new'|null>(null)
 const [activePattern,setActivePattern]=useState<string>(),[drawingId,setDrawingId]=useState<string>()
 const [activeDecor,setActiveDecor]=useState<string>(),[toast,setToast]=useState(''),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false)
 const [priceOpen,setPriceOpen]=useState(false),[hiddenLayers,setHiddenLayers]=useState<Record<string,string[]>>({}),[lightPlaying,setLightPlaying]=useState(false),[lightControlsOpen,setLightControlsOpen]=useState(false)
 const [light,setLight]=useState(0),[nameDraft,setNameDraft]=useState(design.name)
 const n=design.nails[selected],decor=n.decorations.find(d=>d.id===activeDecor)
 const hiddenKey=design.id+':'+selected,hidden=hiddenLayers[hiddenKey]||[]
 const previewDesign={...design,nails:design.nails.map((n,i)=>previewWithoutLayers(n,hiddenLayers[design.id+':'+i]))},displayN=previewDesign.nails[selected]
 const price=designSummary(design)
 const paintLayer=nailPatterns(n).find(l=>l.id===drawingId),drawing=tool==='pattern'&&view==='single'&&!n.artwork&&!n.lockedLayers.includes('pattern')&&paintLayer?.drawMode==='free'&&!paintLayer.locked?paintLayer:undefined
 useEffect(()=>{
  if(!lightPlaying||view!=='single')return
  let frame=0,start=0,last=0
  const tick=(time:number)=>{if(!start)start=time;if(time-start>6000){setLightPlaying(false);setLight(0);return}if(!document.hidden&&time-last>40){setLight(Math.round(Math.sin((time-start)/900)*25));last=time}frame=requestAnimationFrame(tick)}
  frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)
 },[lightPlaying,view])
 function toggleHidden(id:string){setHiddenLayers(old=>({...old,[hiddenKey]:hidden.includes(id)?hidden.filter(x=>x!==id):[...hidden,id]}))}
 function singlePatch(p:Partial<Nail>){commit(updateNails(design,selected,'single',p))}
 function toggleLock(id:string){const patterns=nailPatterns(n),p=patterns.find(l=>l.id===id);if(p){singlePatch(patternPatch(patterns.map(l=>l.id===id?{...l,locked:!l.locked}:l)));return}const d=n.decorations.find(x=>x.id===id);if(d)singlePatch({decorations:n.decorations.map(x=>x.id===id?{...x,locked:!x.locked}:x)});else{const layer=id as Nail['lockedLayers'][number];singlePatch({lockedLayers:n.lockedLayers.includes(layer)?n.lockedLayers.filter(x=>x!==layer):[...n.lockedLayers,layer]})}}
 function removeLayer(id:string){const patterns=nailPatterns(n),p=patterns.find(l=>l.id===id);if(p){if(!p.locked&&!n.lockedLayers.includes('pattern'))singlePatch(patternPatch(patterns.filter(l=>l.id!==id)));setDrawingId(undefined);return}const d=n.decorations.find(x=>x.id===id);if(d){if(!d.locked)singlePatch({decorations:n.decorations.filter(x=>x.id!==id)});return}if(n.lockedLayers.includes(id as Nail['lockedLayers'][number]))return;if(id==='pattern')singlePatch({pattern:'none',patternLayers:[]});if(id==='surface')singlePatch({finish:'gloss'});if(id==='artwork')singlePatch({artwork:undefined})}
 function moveLayer(id:string,direction:number){const patterns=nailPatterns(n),index=patterns.findIndex(l=>l.id===id);if(index>=0){const to=index+direction;if(n.lockedLayers.includes('pattern')||to<0||to>=patterns.length||patterns[index].locked||patterns[to].locked)return;[patterns[index],patterns[to]]=[patterns[to],patterns[index]];singlePatch(patternPatch(patterns));return}const a=n.decorations.findIndex(d=>d.id===id),b=a+direction;if(a<0||b<0||b>=n.decorations.length||n.decorations[a].locked||n.decorations[b].locked)return;const items=[...n.decorations];[items[a],items[b]]=[items[b],items[a]];singlePatch({decorations:items})}

 useEffect(()=>setNameDraft(design.name),[design.name])
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer)},[toast])
 function select(i:number){setDrawingId(undefined);setActivePattern(undefined);setSelected(i);setActiveDecor(undefined);setSide(i<5?'left':'right')}
 function patch(change:Partial<Nail>){const next=updateEditableNails(design,selected,scope,change);if(JSON.stringify(next)===JSON.stringify(design)){setToast('没有改动；请确认图层未锁定，且没有超过图层或笔画数量上限');return}commit(next)}
 function patchDecor(change:Partial<Decoration>){if(decor&&!decor.locked)commit(updateNails(design,selected,'single',{decorations:updateDecoration(n,decor.id,change)}))}
 async function openGallery(){setGallery(true);setGalleryLoading(true);setGalleryError('');try{setSaved(await api<SavedDesign[]>('/api/designs'))}catch(e){setGalleryError((e as Error).message)}finally{setGalleryLoading(false)}}
 async function save(){if(saving)return;setSaving(true);const snapshot={...design,name:nameDraft.trim()||'未命名设计'};commit(snapshot);try{await api(`/api/designs/${snapshot.id}`,{method:'PUT',body:JSON.stringify(snapshot)});setToast('已存入我的作品，可以随时继续设计')}catch(e){setToast((e as Error).message)}finally{setSaving(false)}}
 async function startAtelier(){
  if(saving||!ready)return
  setSaving(true)
  try{await api(`/api/designs/${design.id}`,{method:'PUT',body:JSON.stringify(design)});commit({...applyAtelier(design),id:crypto.randomUUID()});setInspire(false);setView('set');changeArrangement('jewel');setTool('pattern');setToast('已新建玫瑰金线，原设计已留在我的作品')}catch(e){setToast((e as Error).message)}finally{setSaving(false)}
 }
 async function download(){setExporting(true);try{await exportDesign(design,arrangement);setToast('作品图已导出')}catch{setToast('暂时无法导出，请重试')}finally{setExporting(false)}}
 function addDecoration(type:'pearl'|'gem'){
  if(targets(selected,scope).some(i=>design.nails[i].decorations.length>=12)){setToast('每根指甲最多放 12 个饰品');return}
  const id=crypto.randomUUID();commit({...design,nails:design.nails.map((n,i)=>targets(selected,scope).includes(i)?{...n,decorations:[...n.decorations,{id:i===selected?id:crypto.randomUUID(),type,locked:false,x:50,y:78+(n.decorations.length%3)*16,size:type==='pearl'?8:10}]}:n)});setActiveDecor(id);setView('single');setToast('已添加饰品，可拖动或在下方调整')
 }
 return <div className={`app-shell atelier-shell preview-${view}`}><header className="topbar">
  <div className="brand"><span className="brand-mark">j.</span><span>甲间<small>NAIL ATELIER</small></span></div><div className="top-divider"/><div className="project-title"><span>{studio.sandbox?'功能体验 · 原草稿保留':'我的设计'}</span><strong>{design.name}</strong></div>
  <div className="top-actions"><span className={`save-state ${error?'error':''}`} role="status">{status==='正在保存草稿'?<LoaderCircle size={14} className="spin"/>:<span className="status-dot"/>}{status}</span><button className="ghost library-trigger" aria-label="我的作品" onClick={openGallery}><Layers size={16}/><span>我的作品</span></button><button className="primary save-button" disabled={!ready||saving} onClick={save}>{saving?<LoaderCircle size={16} className="spin"/>:<Save size={16}/>}<span>{saving?'保存中':'保存作品'}</span></button></div>
 </header>{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>ready?studio.retry():window.location.reload()}>重试</button></div>}
 <main className="workspace" aria-busy={!ready}><section className="preview-panel" aria-label="甲片与手部预览">
  <div className="preview-toolbar"><div className="segmented view-tabs" role="tablist" aria-label="预览方式">{([{id:'single',label:'单甲'},{id:'five',label:'五指'},{id:'set',label:'十指'},{id:'hand',label:'上手'}] as const).map(v=><button key={v.id} role="tab" aria-selected={view===v.id} className={view===v.id?'active':''} onClick={()=>setView(v.id)}>{v.label}</button>)}</div>{view==='five'&&<div className="segmented five-hand-switch" role="group" aria-label="五指左右手"><button className={side==='left'?'active':''} aria-pressed={side==='left'} onClick={()=>select(selected%5)}>左手</button><button className={side==='right'?'active':''} aria-pressed={side==='right'} onClick={()=>select(selected%5+5)}>右手</button></div>}<button className="material-lab-trigger" onClick={()=>setMaterialLab(true)}>立体试色 <span>新</span></button><div className="history"><button className="icon-button" aria-label="撤销" title="撤销" disabled={!studio.canUndo||!ready} onClick={studio.undo}><Undo2 size={18}/></button><button className="icon-button" aria-label="重做" title="重做" disabled={!studio.canRedo||!ready} onClick={studio.redo}><Redo2 size={18}/></button></div></div>
  {(view==='set'||view==='five')&&<div className="arrangement-toolbar"><span>甲片排列</span><div className="segmented" role="group" aria-label="甲片排列">{([{id:'jewel',label:'珠宝陈列'},{id:'cupped',label:'手心轻拢'},{id:'original',label:'原版排列'}] as const).map(a=><button key={a.id} aria-pressed={arrangement===a.id} className={arrangement===a.id?'active':''} onClick={()=>changeArrangement(a.id)}>{a.label}</button>)}</div></div>}
  {view==='single'&&!n.artwork&&!drawing&&<div className="workbench-light-controls"><button aria-expanded={lightControlsOpen} aria-controls="workbench-light-options" onClick={()=>{const open=!lightControlsOpen;setLightControlsOpen(open);setLightPlaying(open);setLight(0)}}>{lightControlsOpen?'收起灯光':'摇光对照'}</button>{lightControlsOpen&&<div id="workbench-light-options" className="workbench-light-options"><label>灯光位置<input aria-label="展示灯光位置" type="range" min={-25} max={25} value={light} onChange={e=>{setLightPlaying(false);setLight(Number(e.target.value))}}/></label><button onClick={()=>{setLightPlaying(false);setLight(0)}}>灯光归位</button></div>}</div>}
  {drawing&&<div className="drawing-toolbar"><span>{drawing.type==='dots'?'点击甲面放圆点':'按住拖动画线'} · 仅绘制这一指</span><button onClick={()=>setDrawingId(undefined)}>完成绘画</button></div>}
  <div className={`preview-stage ${view}`} onPointerMove={e=>{if(lightControlsOpen&&view==='single'&&!n.artwork&&!lightPlaying&&!activeDecor&&!drawing){const r=e.currentTarget.getBoundingClientRect();setLight(((e.clientX-r.left)/r.width-.5)*35)}}} onPointerLeave={()=>{if(lightControlsOpen&&!lightPlaying)setLight(0)}}>
   {(view==='set'||view==='five')&&arrangement==='jewel'&&<JewelPreview design={previewDesign} selected={selected} hand={view==='five'?side:undefined} onSelect={select} onDetail={i=>{select(i);setView('single')}}/>}
   {(view==='set'||view==='five')&&arrangement==='cupped'&&<GesturePreview design={previewDesign} selected={selected} hand={view==='five'?side:undefined} onSelect={select} onDetail={i=>{select(i);setView('single')}}/>}
   {(view==='set'||view==='five')&&arrangement==='original'&&<div className={`set-layout fan-layout ${view==='five'?'five-nails':'ten-nails'}`}>{(view==='five'?[side==='left'?0:1]:[0,1]).map(hand=><div className="nail-row" key={hand}>{Array.from({length:5},(_,i)=>{const idx=hand*5+i;return <button aria-label={`编辑${nailName(idx)}`} aria-pressed={selected===idx} className={`sheet-nail ${selected===idx?'selected':''}`} key={idx} onClick={()=>select(idx)} onDoubleClick={()=>{select(idx);setView('single')}}><div className={`nail-wrap ${design.nails[idx].length}`}><NailArt nail={previewDesign.nails[idx]}/></div><span>{fingerNames[i]}</span>{selected===idx&&<span className="selected-pin"/>}</button>})}<span className="hand-label">{hand===0?'LEFT / 左手':'RIGHT / 右手'}</span></div>)}</div>}
   {view==='single'&&<div className="single-layout"><button className="icon-button previous" aria-label="上一个指甲" onClick={()=>select((selected+9)%10)}><ArrowLeft size={20}/></button><div className={`single-nail ${n.length}`}><NailArt key={`${selected}:${drawing?.id||'view'}`} nail={displayN} light={light} drawing={drawing?{layerId:drawing.id,onStroke:points=>{
 const layers=nailPatterns(n),current=layers.find(l=>l.id===drawing.id)
 if(!current||current.locked||n.lockedLayers.includes('pattern'))return
 const total=layers.reduce((sum,l)=>sum+l.strokes.reduce((count,s)=>count+s.points.length,0),0)
 if(current.strokes.length>=64||total+points.length>4096){setToast('这一片的笔画已满，请撤回或删除部分笔画后继续');return}
 singlePatch(patternPatch(layers.map(l=>l.id===drawing.id?{...l,strokes:[...l.strokes,{points}]}:l)))
 }}:undefined} selectedDecor={activeDecor} onDecorSelect={setActiveDecor} onDecorMove={(id,x,y)=>commit(updateNails(design,selected,'single',{decorations:updateDecoration(n,id,{x,y})}))}/></div><button className="icon-button next" aria-label="下一个指甲" onClick={()=>select((selected+1)%10)}><ArrowRight size={20}/></button><div className="single-label">{nailName(selected)}<small>{shapeNames[n.shape]} · {finishNames[n.finish]}</small></div></div>}
   {view==='hand'&&<div className="hand-layout"><HandPreview design={previewDesign} side={side} selected={selected} onSelect={select}/><div className="segmented hand-switch"><button className={side==='left'?'active':''} onClick={()=>select(selected%5)}>左手</button><button className={side==='right'?'active':''} onClick={()=>select(selected%5+5)}>右手</button></div></div>}
   <div className="preview-note">{drawing?'可用上方撤销退回上一笔':(view==='set'||view==='five')?'轻点选中指甲 · 双击查看细节':view==='single'?(!n.artwork&&n.finish==='cat'?'移动灯光，看猫眼流动 · 修改后可保存':n.decorations.length?'拖动饰品，找到喜欢的位置':'修改参数即时预览 · 保存后可继续编辑'):'内置手模示意 · 点击甲面继续搭配'}</div>
  </div>{view!=='set'&&<div className="finger-strip" aria-label="选择手指">{previewDesign.nails.map((x,i)=><button key={i} aria-label={`选择${nailName(i)}`} aria-pressed={selected===i} className={selected===i?'active':''} onClick={()=>select(i)}><span className="mini-nail"><NailArt nail={x}/></span><small>{i===0?'左拇':i===5?'右拇':fingerNames[i%5].replace('指','')}</small></button>)}</div>}<footer className="preview-footer"><button className="text-button" disabled={!ready} onClick={()=>setInspire(true)}><Sparkles size={16}/>找一点灵感</button><button className="text-button" onClick={download} disabled={exporting||!ready}>{exporting?<LoaderCircle size={16} className="spin"/>:<Download size={16}/>}导出作品图</button></footer>
 </section><aside className="tools-panel" aria-label="设计工具"><div className="editing-context"><div><span className="eyebrow">DESIGN DETAILS</span><h2>{nailName(selected)}<span>/{String(selected+1).padStart(2,'0')}</span></h2></div><button className="icon-button" title="复制到对应手指" aria-label="复制到对应手指" disabled={!ready} onClick={()=>{const other=(selected+5)%10;commit(updateEditableNails(design,other,'single',structuredClone(n)));setToast(`已复制到${nailName(other)}，锁定内容保持原样`)}}><Copy size={17}/></button></div><div className="scope-row"><span>应用到</span><div className="segmented" role="group" aria-label="修改范围">{([{id:'single',label:'这一指'},{id:'mirror',label:'左右对应'},{id:'all',label:'全部十指'}] as const).map(s=><button key={s.id} aria-pressed={scope===s.id} className={scope===s.id?'active':''} onClick={()=>setScope(s.id)}>{s.label}</button>)}</div></div>
 <ToolPanel patternPanel={<PatternStackControls n={n} patch={patch} active={activePattern} select={id=>{setActivePattern(id);setHiddenLayers(old=>({...old,[hiddenKey]:hidden.filter(x=>x!==id)}))}} drawing={!!drawing} start={()=>{const l=nailPatterns(n).find(l=>l.id===activePattern)||nailPatterns(n).at(-1);if(!l)return;setDrawingId(l.id);setView('single');setLightPlaying(false);setLight(0);setActiveDecor(undefined)}} stop={()=>setDrawingId(undefined)}/>} layerPanel={<DesignLayers n={n} hidden={hidden} onHide={toggleHidden} onLock={toggleLock} onRemove={removeLayer} onMove={moveLayer} onEdit={(next,id)=>{setTool(next);if(id){if(next==='pattern'){setActivePattern(id);setDrawingId(undefined)}else setActiveDecor(id);setView('single')}setHiddenLayers(old=>({...old,[hiddenKey]:hidden.filter(x=>x!==id&&(next!=='color'||!['base','surface'].includes(x))&&(next!=='pattern'||!['pattern','artwork'].includes(x)))}))}}/>} n={n} ready={ready} tool={tool} setTool={value=>{setDrawingId(undefined);setTool(value)}} patch={patch} activeDecor={activeDecor} setActiveDecor={setActiveDecor} add={addDecoration} patchDecor={patchDecor} remove={()=>{if(decor&&!decor.locked){commit(updateNails(design,selected,'single',{decorations:n.decorations.filter(d=>d.id!==decor.id)}));setActiveDecor(undefined)}}} showSingle={()=>setView('single')} reset={()=>setConfirm('reset')}/>
 <button className="price-summary-trigger" onClick={()=>setPriceOpen(true)}><span>整套清单与模拟价 <small>演示 · 非实际报价</small></span><strong>¥{price.total} ›</strong></button><footer className="tools-footer"><label htmlFor="design-name">给作品起个名字</label><div><input id="design-name" value={nameDraft} maxLength={60} disabled={!ready} onChange={e=>setNameDraft(e.target.value)} onBlur={()=>{const name=nameDraft.trim()||'未命名设计';if(name!==design.name)commit({...design,name});else setNameDraft(name)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/><CheckCheck size={16}/></div></footer></aside></main>
 <Dialog open={priceOpen} title="整套设计清单" onClose={()=>setPriceOpen(false)}><PriceDetails design={design}/></Dialog>
 <Dialog open={inspire} title="找一点灵感" onClose={()=>setInspire(false)} wide>{inspire&&<InspirationLibrary design={design} selected={selected} ready={ready&&!saving} onAtelier={startAtelier} onApply={(next,mode)=>{commit(next);setHiddenLayers({});setActiveDecor(undefined);setActivePattern(undefined);setDrawingId(undefined);setLightPlaying(false);setLight(0);setInspire(false);setView(mode==='all'?'set':'single');setToast('灵感已套用，可以继续编辑，也可以撤销恢复')}}/>}</Dialog>
 <Dialog open={gallery} title="我的作品" onClose={()=>setGallery(false)} wide><div className="gallery-toolbar"><p>保存在这台电脑，随时回来继续。</p><button className="ghost" disabled={!ready} onClick={()=>{setGallery(false);setConfirm('new')}}><Plus size={16}/>新建设计</button></div>{galleryLoading?<div className="empty-gallery"><LoaderCircle className="spin"/>正在翻开作品集…</div>:galleryError?<div role="alert" className="empty-gallery">{galleryError}<button onClick={openGallery}>重新加载</button></div>:!saved.length?<div className="empty-gallery"><Layers size={32}/><h3>你的第一套作品，从这里开始</h3><p>回到工作台，点击“保存作品”就会出现在这里。</p><button className="primary" onClick={()=>setGallery(false)}>继续设计</button></div>:<div className="gallery-grid">{saved.map(row=><article className="saved-card" key={row.document.id}><div className="saved-nails">{row.document.nails.slice(0,5).map((n,i)=><NailArt key={i} nail={n}/>)}</div><h3>{row.document.name}</h3><small>{new Date(row.updated_at).toLocaleDateString('zh-CN')}</small><div><button className="ghost" onClick={()=>{commit(row.document);setGallery(false);setView('set');setToast('已打开作品，修改后记得保存作品')}}>继续设计<ArrowRight size={14}/></button><button className="icon-button" aria-label={`复制作品${row.document.name}`} onClick={()=>{commit(duplicateDesign(row.document));setGallery(false);setToast('已创建副本，保存后会出现在作品集')}}><Copy size={16}/></button></div></article>)}</div>}</Dialog>
 <Dialog open={confirm!==null} title={confirm==='new'?'开始一套新设计？':'让甲片重新留白？'} onClose={()=>setConfirm(null)}><p className="dialog-intro">{confirm==='new'?'当前草稿会替换为新设计，已保存的作品仍留在作品集。':`将重置${scope==='all'?'全部十指':scope==='mirror'?'左右对应指':'这一指'}的颜色、图案和饰品。完成后仍可撤销。`}</p><div className="dialog-actions"><button className="ghost" onClick={()=>setConfirm(null)}>先不改</button><button className="primary" onClick={()=>{if(confirm==='new')commit({...newDesign(),name:'新的灵感',nails:Array.from({length:10},baseNail)});else patch(baseNail());setActiveDecor(undefined);setConfirm(null)}}>{confirm==='new'?'开始设计':'确认重置'}</button></div></Dialog>
 {materialLab&&<MaterialLabBoundary onClose={()=>setMaterialLab(false)}><Suspense fallback={<div className="loading-overlay">正在打开立体试色…</div>}><MaterialLab onClose={()=>setMaterialLab(false)}/></Suspense></MaterialLabBoundary>}
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}{!ready&&!error&&<div className="loading-overlay"><LoaderCircle className="spin"/>正在打开你的设计…</div>}
 </div>
}
