import {useLayoutEffect,useRef} from 'react'
import type {CSSProperties,ReactNode} from 'react'
import {Check,ChevronDown,Expand,Flower2,Gem,Layers,Palette,Plus} from 'lucide-react'
import {baseNail,palette,shapeNames,shapes,variantNames} from '../shared/design'
import type {Nail,Decoration} from '../shared/design'
import {NailArt} from './NailArt'
import {Range} from './Widgets'
import {SurfaceControls} from './EffectControls'
import {AtelierLibrary,FinishedStyleControls} from './AtelierLibrary'
export function ToolPanel({n,ready,tool,setTool,patch,activeDecor,setActiveDecor,add,patchDecor,remove,showSingle,reset,layerPanel,patternPanel}:{n:Nail;ready:boolean;tool:string;setTool:(t:string)=>void;patch:(p:Partial<Nail>)=>void;activeDecor?:string;setActiveDecor:(id:string)=>void;add:(type:'pearl'|'gem')=>void;patchDecor:(p:Partial<Decoration>)=>void;remove:()=>void;showSingle:()=>void;reset:()=>void;layerPanel:ReactNode;patternPanel:ReactNode}){
 const scroll=useRef<HTMLDivElement>(null)
 useLayoutEffect(()=>{if(scroll.current)scroll.current.scrollTop=0},[tool])
 const decor=n.decorations.find(d=>d.id===activeDecor)
 const tabs=[{id:'shape',name:'甲型',icon:Expand},{id:'color',name:'底色',icon:Palette},{id:'pattern',name:'图案',icon:Flower2},{id:'decor',name:'饰品',icon:Gem},{id:'layers',name:'图层',icon:Layers}]
 return <><div className="tool-tabs" role="tablist" aria-label="工具分类">{tabs.map(t=><button key={t.id} role="tab" aria-selected={tool===t.id} className={tool===t.id?'active':''} onClick={()=>setTool(t.id)}><t.icon size={20}/>{t.name}</button>)}</div><div ref={scroll} className="tool-scroll">{n.lockedLayers.length>0&&tool!=='layers'&&<button className="lock-notice" onClick={()=>setTool('layers')}>这片甲有锁定内容 · 去图层管理</button>}<fieldset disabled={!ready||(tool==='shape'&&n.lockedLayers.includes('shape'))||(tool==='pattern'&&n.lockedLayers.includes(n.artwork?'artwork':'pattern'))}>
 {n.artwork&&tool!=='decor'&&tool!=='layers'&&<FinishedStyleControls n={n} patch={patch}/>}
 {tool==='shape'&&!n.artwork&&<><div className="section-title"><h3>挑一款喜欢的甲型</h3><span>5 个系列 · 10 款</span></div><div className="shape-library">{shapes.map(s=><section className="shape-family" key={s}><h4>{shapeNames[s]}系列</h4><div className="shape-branches">{(['classic','slim'] as const).map((variant,i)=><button key={variant} aria-label={`选择甲型：${variantNames[s][i]}`} aria-pressed={n.shape===s&&(n.variant||'classic')===variant} className={n.shape===s&&(n.variant||'classic')===variant?'active':''} onClick={()=>patch({shape:s,variant})}><NailArt nail={{...baseNail(),shape:s,variant,color:'#CDB8AB'}}/><strong>{variantNames[s][i]}</strong><small>{String(i+1).padStart(2,'0')} / {variant==='classic'?'CLASSIC':'SLENDER'}</small></button>)}</div></section>)}</div><h3>佩戴长度</h3><div className="choice-grid three">{([{id:'short',label:'短款'},{id:'medium',label:'中长'},{id:'long',label:'长款'}] as const).map(l=><button key={l.id} aria-pressed={n.length===l.id} className={n.length===l.id?'active':''} onClick={()=>patch({length:l.id})}>{l.label}</button>)}</div><p className="helper">同一款可以应用到任何手指，展示大小随手指调整。</p></>}
 {tool==='color'&&!n.artwork&&<><fieldset disabled={n.lockedLayers.includes('base')}><div className="section-title"><h3>给指尖一点颜色</h3><span>{n.color.toUpperCase()}</span></div><div className="color-grid">{palette.map(([label,c])=><button key={c} className={`color-choice ${n.color.toLowerCase()===c.toLowerCase()?'active':''}`} aria-label={`底色：${label}`} aria-pressed={n.color.toLowerCase()===c.toLowerCase()} title={label} style={{'--swatch':c} as CSSProperties} onClick={()=>patch({color:c})}><span>{n.color.toLowerCase()===c.toLowerCase()&&<Check size={17}/>}</span><small>{label}</small></button>)}</div><label className="custom-color"><span><Plus size={15}/>调一个自己的颜色</span><input type="color" aria-label="自定义底色" value={n.color} onChange={e=>patch({color:e.target.value})}/></label><Range label="颜色浓度" value={n.opacity*100} min={35} max={100} suffix="%" onChange={v=>patch({opacity:v/100})}/></fieldset><SurfaceControls n={n} patch={patch}/></>}
 {tool==='pattern'&&!n.artwork&&patternPanel}
 {tool==='pattern'&&<details className="finished-style-library"><summary>成品款式 · 玫瑰金线</summary><AtelierLibrary n={n} patch={patch}/></details>}
 {tool==='layers'&&layerPanel}
 {tool==='decor'&&<>{n.artwork&&<p className="helper">成品款自带的装饰随款式保留；这里管理新添加的珍珠和水钻。</p>}<div className="section-title"><h3>一颗就很特别</h3><span>{n.decorations.length}/12 件</span></div><div className="decor-options"><button onClick={()=>add('pearl')}><span className="pearl-sample"/><span>柔光珍珠</span><Plus size={14}/></button><button onClick={()=>add('gem')}><span className="gem-sample"/><span>冰透水钻</span><Plus size={14}/></button></div>{n.decorations.length===0?<div className="empty-decor"><Gem size={27}/><p>{n.artwork?'继续添一点细节':'留白也很好看'}</p><span>{n.artwork?'这里还没有额外添加的饰品。':'选一颗饰品，或让指尖保持纯净。'}</span></div>:<><h3>这一指的饰品</h3><div className="decor-list">{n.decorations.map((d,i)=><button key={d.id} className={activeDecor===d.id?'active':''} onClick={()=>{setActiveDecor(d.id);showSingle()}}><span>{d.type==='pearl'?'珍珠':'水钻'} {i+1}</span><ChevronDown size={14}/></button>)}</div>{decor&&<fieldset className="detail-box" disabled={decor.locked}><Range label="饰品大小" value={decor.size} min={5} max={18} onChange={v=>patchDecor({size:v})}/><Range label="左右位置" value={decor.x} min={12} max={88} onChange={v=>patchDecor({x:v})}/><Range label="上下位置" value={decor.y} min={20} max={140} onChange={v=>patchDecor({y:v})}/><button className="text-button danger" onClick={remove}>移除这颗饰品</button><p className="helper">位置与大小仅调整当前指甲的这颗饰品；锁定后请先去图层解锁。</p></fieldset>}</>}</>}
 {tool!=='layers'&&<div className="reset-row"><button className="text-button muted" onClick={reset}>重置所选指甲</button></div>}</fieldset></div></>
}
